language: node_js
sudo: required
node_js:
- '0.10'
env:
  global:
  - secure: bZaCNpO8+LFxwo9qmF1w5hw9phonkOWfeKpJusRoeK7A1HnIjhKGJlCM/FPZEy8aRWxH8pjh+2RHWfmFgNz7QX4G/4nJLMLl0tdZ++Exkj8ac8SC5fSBMjRM+rpatfYgRIS6MFiZzoH5hpG4+hX5KgNbTUQPXKozzwoanhwxC7Y=
  - secure: ZrW/iUCriQ9jbBC8/YA/z4QfAs421bAv3SxehSQ/VG/NuLvdIf0ZjlhjksCumdeZpkietk5ZvSSKT30LjpXIoLnVdynjtDAfXVod2MRNgOnJaRTwipyOkGLa/k8/8kDyxzQsu9RYTDOo8ZaSKqFhveHO8HOT0SzUCE1BxJCGzFw=
