ui: tape
browsers:
  - name: chrome
    version: 28..latest
  - name: firefox
    version: 19..latest
  - name: ipad
    version: 4.3..latest
  - name: iphone
    version: 4.3..latest 
  - name: android
    version: 4.0..latest
  - name: opera 
    version: 11..latest 
  - name: internet explorer
    version: 6..latest
